JJ/CC-18-19

objetivos/jmv74211.md
Incorporando los objetivos de jmv74211
=> Incorporando mis objetivos

objetivos/luiisgallego.md
=> Objetivos añadidos

objetivos/AlejandroCN7.md
Fichero de objetivos de Alejandro Campoy Nieves
=> Añadido archivo de objetivos.

objetivos/AlejandroCN7.md
Alumno de Cloud Computing Alejandro Campoy Nieves (nick en Telegram @Alejandrocn7).
=> Actualizado archivo de objetivos de la asignatura.

proyectos/hito-0.md
Alumno Alejandro Campoy Nieves en la asignatura Cloud Computing (nick de Telegram @Alejandrocn7).
=> Actualizada tabla con mi nombre, enlace al repositorio de mi proyecto y versión.

objetivos/danielbc09.md
Primera entrega Hito 0 con Objetivos especificos de la asignatura Cloud Computing
=> Entrega objetivos Daniel

objetivos/jmv74211.md, proyectos/hito-0.md
Actualizo los objetivos de estas dos semanas pasadas y la nueva versión del repositorio.
=> Actualiza objetivos y versión del repositorio

proyectos/hito-0.md
=> Revert "Version 0.1 del proyecto"

proyectos/hito-0.md
=> Revert "Actualizada versión proyecto"

objetivos/jmv74211.md, proyectos/hito-0.md
=> Revert "Actualiza objetivos y versión del repositorio"

objetivos/jabonillab.md
agregar objetivos de la segunda semana
=> objetivos 2

objetivos/alex1ai.md
After the last PR became a disaster (thank you github) I only changed the objetivos file to add the objectives of the second week
=> Add objetivos of the second week

proyectos/hito-1.md
Los cambios realizados en el proyecto han sido:
- Añadir descripción explícita de los microservicios.
- Se han creado varios issues para el hito 1 en relación a los cambios necesarios:
* Enlazar ejercicios teóricos desde los objetivos
* Explicar proyecto en Readme de la rama master
* Explicar microservicios en la descripción.
En cuanto el enlace a los ejercicios teóricos ya lo tenía enlazado en mis objetivos, supongo que no se daría cuenta. Lo único que he hecho es quitar ese enlace del repositorio de mi proyecto.
=> Reenvio hito 1

objetivos/joseramontrillo.md
Son los objetivos de la semana uno de sin rellenar
=> Subida de Objetivos sin rellenar

proyectos/hito-1.md
I made a new fork to delete the wrong commits.
=> Update hito-1 adding my url

sesiones/04-semana.md
Este PR modifica un concepto que podría dar lugar a confusión en los objetivos de la semana 4
=> Modificación de concepto git squash en objetivos de la semana 4

proyectos/hito-1.md
- Se añade el uso de una tecnología de almacenamiento persistente de datos.
- Se especifica el framework web a utilizar basado en el lenguaje elegido inicialmente.
=> Añadiendo descripción más profunda de los servicios usados en el proyecto

proyectos/hito-1.md
comentarios:"No hay descripción de infraestructura a desplegar ni de los componentes necesarios para la misma"
Se hizo la descripción de la Arquitectura y de los componentes 
https://github.com/jabonillab/ProyectoCC2018/issues/4
=> Reenviado hito 1

proyectos/hito-1.md
Comentario: "El README.md no contiene ninguna información ni enlace a la misma sobre servicios y cómo se van a implementar."
Se ha añadido información de los microservicios que van a ser utilizados y cambiada la temática del proyecto.
Issue creado para el comentario: https://github.com/xenahort/proyectoCloudComputing/issues/4
Issue creado para el cambio de temática:  https://github.com/xenahort/proyectoCloudComputing/issues/5
=> Reenvio hito1

proyectos/hito-1.md
Cambios realizados:
- Se ha completado la información del proyecto. Issue 8 y que podemos ver en https://luiisgallego.github.io/MII_CC_1819/
- Se ha actualizado el README con la información del proyecto, aunque esta información se ha resumido respecto a la anterior. Issue 7.
- Se ha cambiado gh-pages por docs. Issue 9.
- Respecto a la corrección me quedaría "realizar un avance significativo". Supongo que esto se refiere a avanzar respecto a los objetivos generales de la asignatura. Esto lo realizaré el próximo viernes y actualizaré el fichero de la asignatura con dichos avances.
=> reenvio el hito

objetivos/AlejandroCN7.md, proyectos/hito-1.md
Corresponde al hito 1 (reenvio)
Es el reenvio del primer hito, con la finalidad de arreglar los errores que tuve en la primera tentativa.
Se han cerrado los issues de despligue, indicación de microservicios, planificación del proyecto y el de arreglar los errores de la primera tentativa perteneciente al hito de definición de la arquitectura a utilizar.
https://github.com/AlejandroCN7/Proyecto-Cloud-Computing/issues?q=is%3Aissue+is%3Aclosed
=> Reenvio del hito 1.

proyectos/hito-1.md
Se hace entrega del hito 1, donde se ha definido  el proyecto que se va a realizar, también se ha explicado la arquitectura del mismo y se ha descrito los microservicios. 
Por otro lado se han creado varios issues y además se han agrupado en 4 milestones.
[Hito 1](https://github.com/jrtrillo/proyecto_cc/issuesq=is%3Aopen+is%3Aissue+milestone%3A%22Hito+1%22)
- [crear hito1](https://github.com/jrtrillo/proyecto_cc/issues/5)
- [definir correctamente el proyecto](https://github.com/jrtrillo/proyecto_cc/issues/6)
- [definir correctamente la arquitectura a utilizar](https://github.com/jrtrillo/proyecto_cc/issues/7)
-[https://github.com/jrtrillo/proyecto_cc/issues/8](https://github.com/jrtrillo/proyecto_cc/issues/8) …
=> Entrega Hito 1

proyectos/hito-1.md
cambié la descripción del proyecto, explicando los diferentes micro servicios y intenté borrar las faltas de ortografía.
=> Reenviado 2

proyectos/hito-1.md
Corresponde al hito 1 Reenviado
Se ha trasladado toda la información reflejada en la página de gh-pages a el README.md
Se ha cerrado un issue que se ha creado especialmente para este reenvío, el issue #5.
=> Cambio de version para reenvio

objetivos/andreamorgar.md
=> Modificado objetivos

objetivos/valtl.md
primer versión de las objetivos de la semana 4.
=> objetivos de la semana 3/4

proyectos/hito-1.md
https://github.com/JJ/CC-18-19/blob/master/objetivos/migueldgoncalves.md
He explicado en README el proyecto. He puesto toda la documentación en una carpeta /docs. La página web del proyecto ahora apunta a otra página que no el README. La compañia ferroviária gestionará una red ferroviária centrada en Granada y no en Sierra Nevada. El framework Ruby on Rails ha sido sustituído por Sinatra. He explicado que servicios voy a usar y cómo se estructuran mis microservicios.
Milestone "Definición del proyecto" https://github.com/migueldgoncalves/CCproj_1819/milestone/2
https://github.com/migueldgoncalves/CCproj_1819/issues/9 - Se describió el proyecto en README …
=> Hito 1 reenviado

objetivos/xenahort.md
https://github.com/JJ/CC-18-19/blob/master/sesiones/04-semana.md
He añadidos los objetivos cumplidos, así como un enlace a ellos.
=> Añadidos objetivos hito 2

objetivos/luiisgallego.md
En el siguiente PR actualizo los objetivos realizados hasta la fecha. Los issues son el 1,2 y 3 aunque no están cerrados ya que faltan actividades por realizar.
=> Objetivos actualizados

objetivos/MarAl15.md
https://github.com/MarAl15/CC-18-19/blob/master/objetivos/MarAl15.md
Se ha añadido los enlaces correspondientes a los distintos objetivos de la segunda semana para que pueda ser verificable que se han conseguido.
=> Añadido enlaces para los objetivos de la segunda semana 

proyectos/hito-1.md
He cambadio la descripcion de la architectura. También aprovecho otras technologias que me parecen bien.
La mayoria pasó en el Issue #2 de mi repositorio pero recientemente actualizé la README sin Issue.
=> Reenviar el hito-1

objetivos/adritake.md
https://github.com/adritake/CC-18-19/blob/master/objetivos/adritake.md
* [ X ] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
* [ X ] He enlazado las actividades con el fichero de objetivos.
* [ X ] He actualizado con la última versión del fichero de entrega y
Añado los objetivos de la cuarta y quinta semana y un enlace a los ejercicios que he hecho del tema 3.
=> Añado objetivos de cuarta y quinta semana

proyectos/hito-2.md
<https://github.com/samahetfield/CC-18-19/blob/master/objetivos/samahetfield.md>
En esta entrega se ha actualizado el proyecto de la asignatura de Cloud Computing. En este caso se ha creado un bot de telegram para estar al tanto de nuestras series favoritas con una funcionalidad mínima que nos permita interactuar con él. Ahora mismo únicamente podemos añadir series a favoritos y ver nuestra lista de series.
Además accediendo a la URL de despligue, se nos devolverá un JSON con {status: OK} demostrando de esta forma el correcto despliegue de la aplicación.
[Hito 2] (https://github.com/samahetfield/PersonalCC-1819/milestone/2)
Issues correspondientes al Hito:
Issue …
=> Añado Hito 2

objetivos/fpeiro.md
Entregados objetivos del hito 2
=> Actualizados objetivos en fpeiro.md

objetivos/gomezportillo.md, proyectos/hito-2.md
despliegue https://apolo-cc.herokuapp.com/
https://github.com/gomezportillo/CC-18-19/blob/master/objetivos/gomezportillo.md
He creado una API REST para manejar una base de datos MongoDB (desplegada en mLab) que se testea en Travis y se despliega automáticamente en Heroku tras pasar los tests.
Para comunicarme con esta API uso las peticiones HTTP GET, POST, PUT y DELETE con los parámetros {'email': $CORREO, 'instrument': $INSTRUMENTO} y el servicio web devuelve mensajes JSON con los resultados. Además, el servidor manda el código HTTP 200 cuando todo es correcto y tiene manejo de los códigos 404 y 405.
[Hito 2: Crear un microservicio y desplegarlo en …
=> Añadiendo hito 2

objetivos/alex1ai.md
[objetivos](https://github.com/alex1ai/CC-18-19/blob/master/objetivos/alex1ai.md)
=> Anade enlace a las ejercicios de PaaS - Objetivos semana 5

proyectos/hito-2.md
[objetivos/adrianmorente.md](https://github.com/JJ/CC-18-19/objetivos/adrianmorente.md)
Entrego el hito 2 de la asignatura, añadiendo código al servicio con las rutas REST y sus operaciones CRUD sobre un almacén de datos (por ahora temporal). Además, se añade configuración y documentación necesaria para testeo automático e integración continua. También se incluye URL del servicio desplegado en Heroku.
[6 Documentación de configuración de los tests](https://github.com/adrianmorente/devtionary/issues/6)
[7 Documentar despliegue a Heroku](https://github.com/adrianmorente/devtionary/issues/7)
[8 Añadir rutas y tests unitarios](https://github.com/adrianmorente/devtionary/issues/8)
=> entrego hito 2

proyectos/hito-2.md
[objetivos/adrianmorente.md](https://github.com/JJ/CC-18-19/objetivos/adrianmorente.md)
Entrego el hito 2 de la asignatura, añadiendo código al servicio con las rutas REST y sus operaciones CRUD sobre un almacén de datos (por ahora temporal). Además, se añade configuración y documentación necesaria para testeo automático e integración continua. También se incluye URL del servicio desplegado en Heroku.
[6 Documentación de configuración de los tests](https://github.com/adrianmorente/devtionary/issues/6)
[7 Documentar despliegue a Heroku](https://github.com/adrianmorente/devtionary/issues/7)
[8 Añadir rutas y tests unitarios](https://github.com/adrianmorente/devtionary/issues/8)
=> reenvío tras modificación de los tests por parte del profesor

proyectos/hito-2.md
[objetivos/alex1ai.md](https://github.com/alex1ai/CC-18-19/blob/master/objetivos/alex1ai.md)
En contrario a los otros (obviamente) he realizado la despliegue con zeit.co. Hay una descripcion de la despliegue enlacando de README, también un fichero del uso del webservice. Se usa travis para pruebas automaticas y despues despliegue del servicio funcionando. 
[Setup Travis](https://github.com/alex1ai/ugr-master-cc/issues/5)
[Initiate Zeit.co](https://github.com/alex1ai/ugr-master-cc/issues/7)
[Create first Webservice](https://github.com/alex1ai/ugr-master-cc/issues/8)
[Write documentation for deployment](https://github.com/alex1ai/ugr-master-cc/issues/9)
[Include Testing](https://github.com/alex1ai/ugr-master-cc/issues/10)
[Document first API …
=> Add hito-2 

objetivos/luiisgallego.md
[Enlace objetivos Luis](https://github.com/luiisgallego/CC-18-19/blob/master/objetivos/luiisgallego.md)
Se han actualizado los objetivos realizados hasta la fecha, con un enlace a los ejercicios del Tema 2 donde corresponde.
=> Actualizo objetivos hasta la semana actual

proyectos/hito-2.md
https://github.com/JJ/CC-18-19/blob/master/objetivos/samahetfield.md
En esta entrega se ha actualizado el proyecto de la asignatura de Cloud Computing. En este caso se ha creado un bot de telegram para estar al tanto de nuestras series favoritas con una funcionalidad mínima que nos permita interactuar con él. Ahora mismo únicamente podemos añadir series a favoritos y ver nuestra lista de series.
Además accediendo a la URL de despligue, se nos devolverá un JSON con {status: OK} demostrando de esta forma el correcto despliegue de la aplicación. Así como una ruta alternativa con la lista de series favoritas que tenemos.
[Hito 2](https://github.com/samahetfield/PersonalCC-1819/milestone/2)
- Añadir test. [Issue …
=> Actualizo versión del proyecto

proyectos/hito-2.md
Todavía no lo he subido, lo subiré a lo largo de la semana. 
Esta es la primera entrega que realizo del hito 2. En este hito, se ha desplegado un servicio rest en un PaaS. En mi caso, se ha hecho un servicio que gestiona predicciones meteorológicas, implementado en Python y Flask y desplegado en Heroku.
Para este hito se ha utilizado un único milestone llamado "Hito 2- Despliegue en un PaaS"
15 [Subir ficheros para desplegar en PaaS](https://github.com/andreamorgar/ProyectoCC/issues/15). Como se ha hecho en otro repositorio de prueba, he movido todos los archivos a este repositorio.
16 [Agregar tests](https://github.com/andreamorgar/ProyectoCC/issues/16) Incorporo los tests …
=> Añadido hito2

objetivos/migueldgoncalves.md
Entrega de fichero de objetivos
https://github.com/JJ/CC-18-19/blob/master/objetivos/migueldgoncalves.md
Objetivos de las semanas 3, 4 y 5.
=> Solo objetivos

proyectos/hito-2.md
https://github.com/luiisgallego/MII_CC_EJERCICIOS_1819/tree/master/Tema2
Pequeño proyecto de inventario completamente desplegado en Herok y testeado en Travis. En él hacemos uso de una API REST para las diferentes tareas de PUT, POST, DELETE y GET.
Para la realización de este proyecto se han realizado un gran numero de issues, siendo los principales los siguientes:
- [#11](https://github.com/luiisgallego/MII_CC_1819/issues/11) Primera versión del proyecto.
- [#12](https://github.com/luiisgallego/MII_CC_1819/issues/12) Añadir tests.
- [#13](https://github.com/luiisgallego/MII_CC_1819/issues/13) Añadir travis al proyecto.
- [#15](https://github.com/luiisgallego/MII_CC_1819/issues/15) Explicación despliegue aplicación.
- …
=> Entrega hito 2.0.2

proyectos/hito-2.md
Corresponde al hito 2.
Entrega del hito 2, en el cual se ha desplegado un microservicio en Heroku encargado de gestionar clientes dentro de un sistema de gestión de incidencias.
Este hito se corresponde con el milestone "Hito 2" de mi proyecto. En él se han cerrado los siguientes issues:
- [Creación de microservicio de login](https://github.com/mesagon/Proyecto-CC-MII/issues/5)
- [Creación microservicio](https://github.com/mesagon/Proyecto-CC-MII/issues/6)
- [Documentación del microservicio](https://github.com/mesagon/Proyecto-CC-MII/issues/7)
=> Reentregar hito 2

objetivos/Objetivos elambri.md
https://github.com/elambri/ejerciciosCC/blob/master/README.md
Objetivos 0
=> Objetivos 0

objetivos/gecofer.md
En el hito 2, he alcanzado los objetivos para la semana 4, 5 y 6.
[https://github.com/Gecofer/ejercicios-CC/tree/master/hito2](https://github.com/Gecofer/ejercicios-CC/tree/master/hito2)
Entrega de los objetivos cumplidos durante la relación del hito 2, que corresponden a la semana 4, 5 y 6.
- [4ª Semana](https://github.com/JJ/CC-18-19/blob/master/sesiones/04-semana.md)
- [5ª Semana](https://github.com/JJ/CC-18-19/blob/master/sesiones/05-semana.md)
- [6ª Semana](https://github.com/JJ/CC-18-19/blob/master/sesiones/06-semana.md)
=> Objetivos hito 2 correspondientes a la semana 4-5-6

proyectos/hito-2.md
https://github.com/jmv74211/CC-Ejercicios/blob/master/Objetivos/semana4.md
Se ha realizado la entrega del hito 2. Básicamente en esta entrega se ha creado un microservicio y se ha desplegado un PaaS llamado Heroku. A este proceso, se le ha añadido integración continua mediante el uso de test y su ejecución automática usando Travis.
Para este hito se ha creado un milestone llamado Hito 2. Dicho milestone consta de los siguientes issues que se han cerrado con esta entrega:
-Microservicio de login y registro de usuarios #19: Desarrollo del microservicio que proveerá las respuestas a las peticiones.
- Test del microservicio login-registro #21: Desarrollo de test para comprobar las salidas esperadas del …
=> Actualiza enlace hito 2

proyectos/hito-2.md
Publicada versión 2 del proyecto con el código y documentación del mismo
* Hito 2
- Subida del proyecto (se ha subido el proyecto)
- Adición de Travis al proyecto (se han añadido los ficheros necesarios para que sea pasado por Travis)
- Información sobre el hito 2 (se ha documentado lo realizado en el proyecto)
=> Publicada versión 2 del proyecto

proyectos/hito-2.md
Solo cambié la numero de version de mi proyecto a una forma MAJOR.MINOR correcta.
=> Update version number of project (1) to actual one (2.2)

objetivos/danielbc09.md
=> Objetivos actualizados para entrega hito 2

proyectos/hito-2.md
* [ x] He leído el guión del hito
* [ x] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [x ] He actualizado con la última versión del fichero de entrega (y resto del repositorio).
Entrgado hito 2. Consiste en el despliegue del proyecto automático en Heroku. Desarrollada la API REST con Flask y el microframework Flask RESTful. Desarrollo basado en pruebas mediante Unittest y Travis, es decir, el despliegue se realiza de forma automática al actualizar el repositorio solo si se pasan los tests creados para el mismo.
Issues del #14 hasta el #21, todos son pertenecientes al Hito llamado "Uso de contenedores para despliegue en la nube".
https://github.com/AlejandroCN7/Proyecto-Cloud-Computing/milestone/4?closed=1
=> Hito 2 realizado (V 2.0)

proyectos/hito-2.md
https://github.com/jrtrillo/proyecto_cc
* [x ] He leído el guión del hito
* [ x] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [ x] He actualizado con la última versión del fichero de entrega (y resto del repositorio).
* [ x] He [seguido las instrucciones para reenvíos](http://jj.github.io/CC/documentos/proyecto/Reenvios) *sólo en caso de reenvío*.
Modiciar archivo index
=> Modificar index

proyectos/hito-2.md
https://github.com/JJ/CC-18-19/blob/master/objetivos/danielbc09.md
* [X ] He leído el guión del hito
* [X ] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [X ] He actualizado con la última versión del fichero de entrega (y resto del repositorio).
* [X ] He [seguido las instrucciones para reenvíos](http://jj.github.io/CC/documentos/proyecto/Reenvios) *sólo en caso de reenvío*.
* [X ] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
* [ X] He enlazado las actividades con el fichero de objetivos.
* [ X] He actualizado con la última versión del fichero de entrega y
Entrega hito 2,  despliegue del servicio de clientes de la aplicación busapp en …
=> Añadido Hito 2

proyectos/hito-2.md
https://github.com/JJ/CC-18-19/blob/master/objetivos/migueldgoncalves.md
Microservicio a implementar el el Hito 2. Contiene un data object, un data access object, una clase de servicio web, una clase main, y dos clases de pruebas. Además contiene los ficheros de configuración necesarios a GitHub, Heroku, Travis y Maven.
Todos los issues aqui presentados pertenencen al milestone https://github.com/migueldgoncalves/CCproj_1819/milestone/8, cerrado en esta entrega.
https://github.com/migueldgoncalves/CCproj_1819/issues/18 Se ha creado el fichero de configuración de Travis
https://github.com/migueldgoncalves/CCproj_1819/issues/20 Se ha actualizado el fichero .gitignore con los archivos de Java, Maven y del IDE …
=> Hito-2 entrega

proyectos/hito-1.md
Actualizado hito 1 con la revisión realizada
* Hito 1
- Se han descrito los servicios que se van a utilizar
- Se han descrito los datos que se van a almacenar
- Se ha descrito cómo se comunican los servicios a implementar
- Se ha descrito la arquitectura utilizada
=> Reenvío del Hito 1

objetivos/Objetivos elambri.md
Entrega de fichero de objetivos
=> objetivos de las semanas (2 - 3)

objetivos/AntonioJavierRP.md
https://github.com/AntonioJavierRP/CC-18-19/blob/master/objetivos/AntonioJavierRP.md
He actualizado mi fichero de objetivos semanales con lo hecho hasta el momento
=> Actualizado mi fichero de objetivos

objetivos/gomezportillo.md
https://github.com/gomezportillo/CC-18-19/blob/master/objetivos/gomezportillo.md
Actualizado el fichero de objetivos con la quinta semana
=> actualizando los hitos de la semana 5

objetivos/adritake.md
https://github.com/adritake/CC-18-19/blob/master/objetivos/adritake.md
Entrego los objetivos de la semana 7
=> Añado objetivos

proyectos/hito-2.md
Actualizado hito 2 con la revisión realizada
* Hito 2
- Se ha documentado el Procfile, los package.json y package-lock.json y el .travis.yml
- Se ha documentado el despliegue desde GitHub
=> Reenvío del Hito 2

proyectos/hito-2.md
He arreglado el enlace de la documentacion.
Hito 2:
* Arreglar documentacion
* Incluir ficheros al gitignore
* Revisar travis.yml
=> Reenvio Hito 2

objetivos/javiercabrera184.md, proyectos/hito-2.md
https://github.com/javiercabrera184/CC-18-19/blob/objetivos/objetivos/javiercabrera184.md
Objetivos semana 5,6,7
=> Objetivos hito 3

objetivos/xenahort.md
https://github.com/JJ/CC-18-19/blob/master/objetivos/xenahort.md
Añadidos los objetivos correspondientes al hito 3
=> Añado objetivos hito 3

proyectos/hito-2.md
Reenvío del Hito 2, he puesto el enlace a la documentación en el readme de la página principal del repositorio, he corregido faltas de ortografía, la documentación,... en base a los comentarios dichos sobre la anterior entrega.
Se ha terminado el hito 2 con el cierre del siguiente issue:
[Correción del hito 2](https://github.com/AntonioJavierRP/Cloud-Computing-Project/issues/7)
=> Añadido mi reenvío del hito 2

objetivos/MarAl15.md
https://github.com/MarAl15/CC-18-19/blob/master/objetivos/MarAl15.md
Objetivos cumplidos mediante la realización de diferentes ejercicios relacionados con el hito 3 y consulta de información.
=> Objetivos relacionados con el hito 3

proyectos/hito-2.md
https://github.com/JJ/CC-18-19/blob/master/objetivos/samahetfield.md
Actualizo el proyecto, eliminando la funcionalidad del bot existente y creando un servicio web para almacenar películas y modificando los test.
[Hito 2](https://github.com/samahetfield/PersonalCC-1819/milestone/2)
- [Receta del sistema de aprovisionamiento](https://github.com/samahetfield/PersonalCC-1819/issues/4)
- [Infraestructura PaaS](https://github.com/samahetfield/PersonalCC-1819/issues/5)
- [Añadir test](https://github.com/samahetfield/PersonalCC-1819/issues/6)
- [Sistema local o remoto](https://github.com/samahetfield/PersonalCC-1819/issues/7)
- [Modificar los tests](https://github.com/samahetfield/PersonalCC-1819/issues/8)
- …
=> Reenvío hito2

proyectos/hito-1.md
=> resend Hito1

objetivos/alex1ai.md
[objetivos](https://github.com/alex1ai/CC-18-19/blob/master/objetivos/alex1ai.md)
Update de los objetivos de las semanas pasadas.
=> Anade semanas 6-8

objetivos/mesagon.md
https://github.com/mesagon/CC-18-19/blob/master/objetivos/mesagon.md#sexta-semana
Entrega de objetivos de las semanas 6, 7 y 8.
=> Añadir objetivos hasta semana 8

proyectos/hito-3.md
Publicada versión 3 del proyecto con el código y documentación del mismo
* Hito 3
- Adición de provisionamiento al proyecto (se ha provisionado haciendo uso de Ansible)
- Información sobre el hito 3 (se ha documentado lo realizado en el proyecto)
- Adición de gráficas al proyecto (se han preparado las gráficas para una futura funcionalidad)
- Adición de las comprobaciones de despliegue (se añade la comprobación del proyecto por gomezportillo)
=> Publicada versión 3 del proyecto

proyectos/hito-2.md
=> Hito 2 Reenviado

proyectos/hito-3.md
[objetivos](https://github.com/JJ/CC-18-19/blob/master/objetivos/alex1ai.md) 
Escribé playbook de ansible y una documentación como se la utiliza. 
Milestone: Hito3: Configuracion de VM
Issues:
- [Create Playbook for Ansible](https://github.com/alex1ai/ugr-master-cc/issues/4) 
- [Documentation of provision](https://github.com/alex1ai/ugr-master-cc/issues/19)
=> Anade hito-3

objetivos/gecofer.md, proyectos/hito-3.md
* [x ] He leído el guión del hito
* [x ] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [x ] He actualizado con la última versión del fichero de entrega (y resto del repositorio).
Descripción del despliegue de la infraestructura en máquina virtual local y en máquina virtual de Azure con la realización del provisionamiento en Ansible para el servicio desarrollado.
Correspondiente al milestone: [https://github.com/Gecofer/proyecto-CC/milestone/3](https://github.com/Gecofer/proyecto-CC/milestone/3)
- Avance en la aplicación con respecto al hito anterior
- Documentación que explique la extracción de datos de la API de Twitter
- Añadir un índice en el README principal
- Documentar en un archivo los avances del proyecto
- Provisionamiento de mv …
=> Añadido enlace hito 3 versión 3.0 (tag hito3-v1.1)

proyectos/hito-3.md
https://github.com/JJ/CC-18-19/blob/master/sesiones/06-semana.md
https://github.com/JJ/CC-18-19/blob/master/sesiones/07-semana.md
https://github.com/JJ/CC-18-19/blob/master/sesiones/08-semana.md
Se ha creado una receta de provisionamiento, un playbook Ansible, para provisionar una máquina virtual Azure y desplegar en ella la aplicación. Se ha actualizado la documentación con un tutorial para crear y provisionar la máquina virtual y desplegar en ella la aplicación, así como una explicación detallada del playbook. Además, se ha movido documentación referente a hitos anteriores a ficheros colocados en /docs enlazados desde README.
Todos los issues cerrados pertenencen al mismo milestone, …
=> Entrega hito-3

proyectos/hito-3.md
Actualizé el proyecto con un servidor de logging para mejorar el webservice. Como es un task de este hito 3, hago este PR.
[Create logging](https://github.com/alex1ai/ugr-master-cc/issues/18)
=> reentregar hito-3

proyectos/hito-3.md
https://github.com/JJ/CC-18-19/blob/master/objetivos/gomezportillo.md
He creado una máquina virtual en azure y escrito los archivos necesarios de ansible para provisionarla automáticamente.
[Hito 3: Provisionamiento con Ansible](https://github.com/gomezportillo/apolo/milestone/3)
* [provisionar con ansible](https://github.com/gomezportillo/apolo/issues/9)
* [Arreglar las URIs del servidor para leer y borrar todos los usuarios](https://github.com/gomezportillo/apolo/issues/10)
* [arregar el proyecto para pasar los tests](https://github.com/gomezportillo/apolo/issues/11)
* [añadir pruebas gráficas del testing de ansible](https://github.com/gomezportillo/apolo/issues/13)
=> Añadiendo el hito 3

proyectos/hito-3.md
**Nota:** Los iré añadiendo a lo largo de la semana. Tengo algunos ficheros hechos pero no subidos.
Entrega correspondiente al hito número 3
He desarrollado un nuevo microservicio, aprovisionado una máquina virtual con ansible, desplegado en azure y corregido el aprovisionamiento a @gecofer
He cerrado el milestone correspondiente al hito número 3. Los issues cerrados son los siguientes:
- **Configuración de vagrant:** Configuración de vagrant para crear máquinas virtuales y aprovisionarlas con ansible automáticamente.
- Corregir aprovisionamiento a @Gecofer: He corregido el aprovisionamiento de la compañera y lo he documentado todo.
- Configuración del sistema de aprovisionamiento: Instalación y configuración para el aprovisionamiento de la máquina.
- Añade nueva …
=> Añade nueva versión del hito 3

objetivos/luiisgallego.md
https://github.com/JJ/CC-18-19/blob/master/objetivos/luiisgallego.md
Se han actualizado los objetivos con los realizados hasta la novena semana incluidos.
=> añado objetivos realizados hasta la fecha

proyectos/hito-3.md
https://github.com/JJ/CC-18-19/blob/master/objetivos/MarAl15.md#septima-semana
Para este hito se ha ampliado la funcionalidad añadiendo del microservicio de extracción de la lista de científicos ganadores del premio Nobel de Física, además se ha creado y aprovisionado con Ansible una máquina virtual creada en Azure.
[Hito 3: Provisionamiento de máquinas virtuales](https://github.com/MarAl15/ProyectoCC/milestone/3)
- [Nueva funcionalidad](https://github.com/MarAl15/ProyectoCC/issues/15): Se ha añadido el microservicio de extracción de la lista de científicos ganadores del premio Nobel de Física realizando los cambios correspondientes y documentado brevemente.
- [Aprovisionamiento](https://github.com/MarAl15/ProyectoCC/issues/14): Creación del _playbook_ para el …
=> Enlace al repo y version hito3

proyectos/hito-3.md
**Nota:** Los iré añadiendo a lo largo de la semana. Tengo algunos ficheros hechos pero no subidos.
Entrega correspondiente al hito número 3
He desarrollado un nuevo microservicio, aprovisionado una máquina virtual con ansible, desplegado en azure y corregido el aprovisionamiento a @gecofer
He cerrado el milestone correspondiente al hito número 3. Los issues cerrados son los siguientes:
- **Configuración de vagrant:** Configuración de vagrant para crear máquinas virtuales y aprovisionarlas con ansible automáticamente.
- Corregir aprovisionamiento a @Gecofer: He corregido el aprovisionamiento de la compañera y lo he documentado todo.
- Configuración del sistema de aprovisionamiento: Instalación y configuración para el aprovisionamiento de la máquina.
- Añade nueva …
=> Actualiza version del hito3

objetivos/danielbc09.md
=> Actualización objetivos hito 3

objetivos/adrianmorente.md, proyectos/hito-3.md
[objetivos/adrianmorente.md](https://github.com/adrianmorente/devtionary)
A lo largo de este hito 3, he incorporado a mi servicio web el provisionamiento de máquinas virtuales basado en Ansible. Gracias a esto, he podido ejecutar mi servicio en una máquina alojada por Microsoft en Azure. Además, como avance adicional he utilizado un sistema de logs automático como es Winston, para NodeJS.
[Hito 3](https://github.com/adrianmorente/devtionary/issues/3)
[Hito 4](https://github.com/adrianmorente/devtionary/issues/4)
[Hito 5](https://github.com/adrianmorente/devtionary/issues/5)
[Hito 13](https://github.com/adrianmorente/devtionary/issues/13)
[Hito 14](https://github.com/adrianmorente/devtionary/issues/14)
[Hito …
=> Entrego hito 3

objetivos/adrianmorente.md
[objetivos/adrianmorente.md](https://github.com/JJ/CC-18-19/objetivos/adrianmorente.md)
Entrego en un pull request aparte el fichero de objetivos correspondiente hasta la novena semana (en la que finaliza la entrega del hito 3).
=> añadiendo semanas pasadas + objetivos de la novena semana

proyectos/hito-1.md
https://github.com/JJ/CC-18-19/commit/abe3b4e2a9ef2188f7bd4dc722bd5ebff59c63ce
Description of the project
https://github.com/elambri/proyectoCC/milestone/5
=> Hito correction..

objetivos/jabonillab.md, proyectos/hito-3.md
o
https://github.com/JJ/CC-18-19/blob/master/objetivos/jabonillab.md
* [x ] He leído el guión del hito
* [x ] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [ x] He actualizado con la última versión del fichero de entrega (y resto del repositorio).
* [x ] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
* [ x] He enlazado las actividades con el fichero de objetivos.
* [ x] He actualizado con la última versión del fichero de entrega y
Hito 3 de Aprovisionamiento
=> obj jabonillab

proyectos/hito-3.md
Hize todas las cosas que me daban menos puntos:
- Anadí justificacion por el OS
- Hize comprobacion con otro estudiante
Documentación se encuentra [aqui](https://github.com/alex1ai/ugr-master-cc/blob/gh-pages/provision.md)
[Terminar hito-3](https://github.com/alex1ai/ugr-master-cc/issues/20)
=> Reentrega hito-3

proyectos/hito-3.md
https://github.com/JJ/CC-18-19/blob/master/sesiones/06-semana.md
https://github.com/JJ/CC-18-19/blob/master/sesiones/07-semana.md
https://github.com/JJ/CC-18-19/blob/master/sesiones/08-semana.md
Se ha añadido la documentación de la comprobación tanto de playbooks de compañeros como de mi playbook. Además, se ha movido la documentación de la arquitectura del proyecto del README a un fichero en /docs enlazado desde README. Se ha también corregido la ortografia de la documentación.
Todos los issues cerrados pertenencen al milestone correspodiente a este hito:
https://github.com/migueldgoncalves/CCproj_1819/milestone/3
https://github.com/migueldgoncalves/CCproj_1819/issues/28 Se ha añadido la documentación de la …
=> Reenvio hito-3

proyectos/hito-3.md
Los subiré durante esta semana
Entrega del hito 3 de la asignatura, en el que he desplegado mi aplicación de planificación deportiva en una máquina virtual de Azure, la he aprovisionado con Ansible y añadido una nueva funcionalidad al proyecto.
Se ha terminado el hito 3 que consta de los siguientes issues:
[Añadir funcionalidad al proyecto](https://github.com/AntonioJavierRP/Cloud-Computing-Project/issues/8)
[Documentar funcionalidad](https://github.com/AntonioJavierRP/Cloud-Computing-Project/issues/9)
[Documentar provisionamiento](https://github.com/AntonioJavierRP/Cloud-Computing-Project/issues/10)
[Documentar infraestructura](https://github.com/AntonioJavierRP/Cloud-Computing-Project/issues/11)
[Documentar creación de …
=> Añadido enlace a mi proyecto para Hito 3.

objetivos/gomezportillo.md
https://github.com/gomezportillo/CC-18-19/blob/master/objetivos/gomezportillo.md
Entrega de los objetivos y añadido la fecha  de inicio a cada semana.
=> actualizando objetivos

proyectos/hito-4.md
https://github.com/JJ/CC-18-19/blob/master/objetivos/gomezportillo.md
He creado un script (RAIZ/acopio/acopio.sh) para automatizar la creación de máquinas virtuales a través del CLI de Azure.
Este script pregunta al usuario por los diferentes parámetros necesarios antes de crear cuantas máquinas le indique.
[Hito 4: Automatización de creación de VM con el CLI de Azure](https://github.com/gomezportillo/apolo/milestone/5)
* [instalar el CLI de azure](https://github.com/gomezportillo/apolo/issues/18)
* [automatización de la creación de MV](https://github.com/gomezportillo/apolo/issues/14)
* [realizar pruebas de velocidad entre dos centros de datos europeos de azure](https://github.com/gomezportillo/apolo/issues/17)
* [indicar a través de argumentos los parámetros de la …
=> añadiendo hito 4

objetivos/javiercabrera184.md
https://github.com/javiercabrera184/CC-18-19/blob/master/objetivos/javiercabrera184.md
Objetivos del hito 4
=> Añado objetivos Hito 4

objetivos/adritake.md
https://github.com/adritake/CC-18-19/blob/master/objetivos/adritake.md
Entrega de los objetivos de la novena semana hasta ahora
=> Añado objetivos semana 9

objetivos/samahetfield.md
https://github.com/samahetfield/CC-18-19/blob/master/objetivos/samahetfield.md
Entrega de los objetivos de las semanas 9 y 10.
=> Añado objetivos semanas 9-10

proyectos/hito-4.md
Entrega del Hito 4. Se ha realizado el script de acopio, asi como tambien añadido MongoDB a la aplicacion. Por ultimo, se ha documentado todo el proceso
Hito 4
* Issue # 13: Añadir MongoDB
* Issue # 14: Realizar script de Acopio
* Issue # 15: Documentacion del Hito
=> Añado Hito 4

proyectos/hito-3.md
https://github.com/JJ/CC-18-19/blob/master/objetivos/MarAl15.md
Creación de una nueva MV en Azure explicando las distintas elecciones para llevar a cabo su configuración, realización del aprovisionamiento con Ansible y despligue en la MV. Además se ha añadido una base de datos para la gestión de tareas. 
[Hito 3: Provisionamiento de máquinas virtuales](https://github.com/MarAl15/ProyectoCC/milestone/3)
- [Base de datos de las tareas :](https://github.com/MarAl15/ProyectoCC/issues/18) Se ha modificado los ficheros oportunos para manejar la base de datos para la gestión de tareas utilizando mongoose.
- [Aprovisionamiento:](https://github.com/MarAl15/ProyectoCC/issues/14) Se ha modificado el fichero de aprovisionamiento instalando e inicializando MongoDB, además de …
=> Nueva versión envío

objetivos/mesagon.md
=> Añado objetivos semanas 9 y 10

proyectos/hito-4.md
Publicada versión 4 del proyecto con el código y documentación del mismo
* [Hito 4](https://github.com/fpeiro/CC-proyecto/milestone/5)
- [Adición de automatización al proyecto](https://github.com/fpeiro/CC-proyecto/issues/17) (se ha automatizado haciendo uso de Azure CLI)
- [Información sobre el hito 4](https://github.com/fpeiro/CC-proyecto/issues/19) (se ha documentado lo realizado en el proyecto así como  la elección de centro de datos y de imagen)
- [Adición del CRUD de valores](https://github.com/fpeiro/CC-proyecto/issues/18) (se ha creado el segundo microservicio correspondiente con la introducción de datos a sensores y gráficas)
=> Publicada versión 4 del proyecto

objetivos/gecofer.md
Entrega de fichero de objetivos de las semanas 9-10-11
- [Enlace al fichero de objetivos](https://github.com/Gecofer/CC-18-19/blob/master/objetivos/gecofer.md)
- [Ejercicios para el hito 4](https://github.com/Gecofer/ejercicios-CC/tree/master/hito4)
- [Objetivos cumplidos en el hito en el apartado de Novedades](https://github.com/Gecofer/proyecto-CC#id0)
Objetivos cumplidos a lo largo del hito 4, además se encuentran dichas respuestas en el proyecto.
=> Objetivos semana 9-10-11

proyectos/hito-3.md
https://github.com/jrtrillo/proyecto_cc
Entrega hito 3
https://github.com/jrtrillo/proyecto_cc/issues/14
https://github.com/jrtrillo/proyecto_cc/issues/13
https://github.com/jrtrillo/proyecto_cc/issues/12
=> subir hito3

proyectos/hito-4.md
[objetivos](https://github.com/alex1ai/CC-18-19/blob/master/objetivos/alex1ai.md)
- Provisionamento automatico por script acopio.sh
- Ansible playbook update
- Anadí MongoDB a mi servicio web
[Hito 4](https://github.com/alex1ai/ugr-master-cc/milestone/6)
Milestones:
- [21: Choose VM and stress test](https://github.com/alex1ai/ugr-master-cc/issues/21)
- [22: Documentation](https://github.com/alex1ai/ugr-master-cc/issues/22)
- [23: Setup acopio.sh](https://github.com/alex1ai/ugr-master-cc/issues/23)
=> agregar hito 4

proyectos/hito-4.md
Entrega del hito 4, consistente en la automatización de creación de máquinas virtuales mediante un script utilizando los comandos del CLI de Azure.
- [Gestion de logs](https://github.com/mesagon/Proyecto-CC-MII/issues/13): Añadir gestión de logs mediante logstash.
- [Provisionamiento](https://github.com/mesagon/Proyecto-CC-MII/issues/14): Creación de los playbooks para el provisionamiento.
- [Manejar errores con excepciones](https://github.com/mesagon/Proyecto-CC-MII/issues/15): Adaptar el microservicio para gestionar los errores con excepciones.
- [Acortar readme](https://github.com/mesagon/Proyecto-CC-MII/issues/16): Resumir el documento principal del proyecto.
- [Crear …
=> Entregar hito 4

proyectos/hito-4.md
Hito 4 (Automatización desde línea de ordenes, y avance del proyecto con logs)
Todo es referente al Milestone: Hito4 - Automatización desde línea de órdenes
#45 Actualizar info web
#43 Documentar avance del proyecto
#42 Documentar automatización
#44 Modificar tests
#39 Reestructurar Readme
=> Añado hito4

objetivos/xenahort.md
https://github.com/xenahort/CC-18-19/blob/master/objetivos/xenahort.md
=> Añadidos objetivos hito 4

objetivos/migueldgoncalves.md
https://github.com/JJ/CC-18-19/blob/master/sesiones/09-semana.md
https://github.com/JJ/CC-18-19/blob/master/sesiones/10-semana.md
https://github.com/JJ/CC-18-19/blob/master/sesiones/11-semana.md
Objetivos de las semanas 9 a 11
=> Objetivos semanas 9 a 11

proyectos/hito-4.md
Actualizado hito 4 con la revisión realizada
* [Hito 4](https://github.com/fpeiro/CC-proyecto/milestone/5)
- Se ha hecho un benchmark sobre distintos sistemas operativos para la elección de la imagen
- Se ha documentado la elección del tamaño de la imagen
=> Reenvío del Hito 4

proyectos/hito-4.md
https://github.com/JJ/CC-18-19/blob/master/objetivos/samahetfield.md
Reenvío del hito 4 corrigiendo errores del script de automatización.
[Hito 4](https://github.com/samahetfield/PersonalCC-1819/milestone/4)
[Añadir acopio.sh](https://github.com/samahetfield/PersonalCC-1819/issues/17)
[Comprobar latencia de regiones de azure](https://github.com/samahetfield/PersonalCC-1819/issues/18)
[Editar documentación](https://github.com/samahetfield/PersonalCC-1819/issues/19)
[Corregir errores hito4](https://github.com/samahetfield/PersonalCC-1819/issues/20)
=> Reenvío hito4

proyectos/hito-2.md
=> resend Hito2

objetivos/luiisgallego.md
https://github.com/luiisgallego/CC-18-19/blob/master/objetivos/luiisgallego.md
Se ha actualizado los objetivos de la asignatura realizados hasta el día de hoy.
=> objetivos actualizados hasta hoy

objetivos/jrtrillo.md
https://github.com/JJ/CC-18-19/blob/master/sesiones/11-semana.md
Actualización de objetivos
=> añade objetivos

objetivos/AlejandroCN7.md
Entrega de fichero de objetivos AlejandroCN7.md 
=> Actualizados objetivos AlejandroCN7.md

proyectos/hito-4.md
https://github.com/javiercabrera184/CC-18-19/blob/master/objetivos/javiercabrera184.md
Reenvio del Hito 4. Actualizacion del script de acopio, asi como la documentacion del proyecto y justificaciones que se piden.
Hito 4
* Issue # 13: Añadir MongoDB
* Issue # 14: Realizar script de Acopio
* Issue # 15: Documentacion del Hito
=> Reenvio Hito 4

proyectos/hito-3.md
=> added Hito3

proyectos/hito-4.md
Entrega del hito 4, en el que se han comparado las diferentes partes a elegir a la hora de crear una máquina virtual en la nube y se ha aprendido a desplegarlas mediante línea de órdenes, además de esto se ha ampliado la aplicación.
[Hito 4](https://github.com/AntonioJavierRP/Cloud-Computing-Project/milestone/4) que consta de las siguientes issues:
[Añadir funcionalidad](https://github.com/AntonioJavierRP/Cloud-Computing-Project/issues/20)
[Documentar funcionalidad](https://github.com/AntonioJavierRP/Cloud-Computing-Project/issues/21)
[Documentación Hito 4](https://github.com/AntonioJavierRP/Cloud-Computing-Project/issues/18)
[Corregir errores y bugs](https://github.com/AntonioJavierRP/Cloud-Computing-Project/issues/19)
=> Añadido el enlace al repositorio de mi proyecto en el Hito 4

proyectos/hito-5.md
He creado un script de Vagrant que permite orquestar máquinas virtuales en Azure y lo he documentado adecuadamente, además de avanzar en la parte del servidor y arreglar pequeños errores. Además, he testeado el archivo vagrant de un compañero y han testeado el mío.
[Htio 5: Orquestación con Vagrant](https://github.com/gomezportillo/apolo/milestone/6)
* [Documentar Vagrant](https://github.com/gomezportillo/apolo/issues/22)
* [Modificar el servidor para acceder a los datos a través de sus URI](https://github.com/gomezportillo/apolo/issues/24)
* [[BUG] Arreglar el método find() del DAO de usuarios](https://github.com/gomezportillo/apolo/issues/30)
* [Implementar el patrón singleton en el DAO de usuarios por medio de un …
=> Añadiento hito 5

proyectos/hito-4.md
=> added link of hito4

proyectos/hito-5.md
Publicada versión 5 del proyecto con el código y documentación del mismo
* [Hito 5](https://github.com/fpeiro/CC-proyecto/milestone/6)
- [Adición de orquestación al proyecto](https://github.com/fpeiro/CC-proyecto/issues/20) (se ha realizado la orquestación haciendo uso de Vagrant)
- [Información sobre el hito 5](https://github.com/fpeiro/CC-proyecto/issues/21) (se ha documentado lo realizado en el proyecto así como la integración con el resto de servicios)
- [Adición del CRUD de alertas](https://github.com/fpeiro/CC-proyecto/issues/23) (se ha creado el tercer microservicio correspondiente con la creación de alertas sobre los valores de los …
=> Publicada versión 5 del proyecto

objetivos/samahetfield.md
https://github.com/samahetfield/CC-18-19/blob/master/objetivos/samahetfield.md
Entrega de los objetivos de la semana 11 correspondientes al tema de orquestación.
=> Añado objetivos semana 11

objetivos/mesagon.md
https://github.com/mesagon/CC-18-19/blob/master/objetivos/mesagon.md#und%C3%A9cima-semana
Objetivos de las semanas 11 y 12.
=> Añado objetivos semanas 11 y 12

proyectos/hito-5.md
Entrega del hito 5 del proyecto. En el cual se ha adecuado el microservicio de gestión de clientes para que utilice una base de datos en MongoDB y se han orquestado dos MVs mediante Vagrant.
[Hito 5](https://github.com/mesagon/Proyecto-CC-MII/milestone/5)
- [Documentación](https://github.com/mesagon/Proyecto-CC-MII/issues/19): Documentación de las tareas realizadas en el hito.
- [Implementar login](https://github.com/mesagon/Proyecto-CC-MII/issues/20): Adecuación del microservicio para que en un futuro pueda tener login para identificar a los clientes. 
- [Implementar base de datos](https://github.com/mesagon/Proyecto-CC-MII/issues/21): …
=> Añadir enlace de mi proyecto al hito 5

proyectos/hito-5.md
https://github.com/javiercabrera184/CC-18-19/blob/master/objetivos/javiercabrera184.md
Entrega del hito 5 de CC. Se ha realizado la orquestacion con vagrant y el desarrollo de un servicio de login.
Hito 5
* Issue 16: Documentacion del proyecto
* Issue 17: Desarrollo de un Vagrantfile
* Issue 18: Provisionar a un compañero
* Issue 19: Realizar un servicio de login.
=> Añado Hito 5

proyectos/hito-5.md
[enlace objetivos](https://github.com/JJ/CC-18-19/blob/master/objetivos/alex1ai.md)
He anadido orchestacion con vagrant al proyecto y he cambiado unos cosas en el proyecto propio.
[Milestone 5: Orchestacion](https://github.com/alex1ai/ugr-master-cc/milestone/7)
Issues:
- [Provison por Vagrant](https://github.com/alex1ai/ugr-master-cc/issues/28)
- [Documentacion del hito](https://github.com/alex1ai/ugr-master-cc/issues/29)
=> Entrega hito 5, v5.0

proyectos/hito-3.md
https://github.com/JJ/CC-18-19/blob/master/objetivos/MarAl15.md
- Se ha modificado la descripción y arquitectura del proyecto, eliminando el calendario de premios Nobel. 
- Se ha arreglado Travis CI conectándonos a la base de datos cada vez que queramos realizar una operación sobre esta y cerrándola tras ello. Además de corregir el manejo de errores.
- Se ha modificado la explicación del sistema operativo elegido para lo cual se ha testeado el rendimiento de la aplicación utilizando Apache Benc en tres sistemas operativos. 
- Se ha añadido una breve explicación en la elección de curl y forever.
[Hito 3: Provisionamiento de máquinas virtuales](https://github.com/MarAl15/ProyectoCC/milestone/3)
- [Correcciones:](https://github.com/MarAl15/ProyectoCC/issues/19) Se ha …
=> Reentrega hito

proyectos/hito-5.md
Entrega del hito 5. Para este hito he creado toda la funcionalidad necesaria para guardar los hitos en una base de datos mongodb. Ademas se ha creado todo lo necesario para orquestar una MV con mongodb y que se conecte con la MV del servicio. Aunque no sea mucho también se ha incluido el badge de travis con el estado del build del repositorio en el readme.
[Hito 5](https://github.com/adritake/CC_UGR_Personal/milestone/5)
[#40](https://github.com/adritake/CC_UGR_Personal/issues/40) Incluir badge travis
[#41](https://github.com/adritake/CC_UGR_Personal/issues/41) Crear vagrant file
[#42](https://github.com/adritake/CC_UGR_Personal/issues/42) Documentar orquestación
[#43](https://github.com/adritake/CC_UGR_Personal/issues/43) Crear server de mongodb …
=> Entrego hito 5

proyectos/hito-5.md
o
Entrega del hito 5 correspondiente a la orquestación con Vagrant.
[Hito 5](https://github.com/samahetfield/PersonalCC-1819/milestone/5)
- [Modificar test](https://github.com/samahetfield/PersonalCC-1819/issues/23)
- [Añadir funcionalidad](https://github.com/samahetfield/PersonalCC-1819/issues/22)
- [Modificar documentación](https://github.com/samahetfield/PersonalCC-1819/issues/24)
=> Añado enlace hito 5

objetivos/jrtrillo.md, proyectos/hito-3.md
Corresponde al hito 3 Reenvio
https://github.com/jrtrillo/proyecto_cc
Corregido el hito 3 con las indicaciones propuestas por el profersor.
https://github.com/jrtrillo/proyecto_cc/issues/18
=> Reenvio hito 3

objetivos/MarAl15.md
https://github.com/MarAl15/CC-18-19/blob/master/objetivos/MarAl15.md#novena-semana
Actualización de los objetivos correspondientes al hito 4, enlazándolo con las actividades realizadas para lograrlos.
=> Objetivos hito 4

objetivos/luiisgallego.md
https://github.com/luiisgallego/CC-18-19/blob/master/objetivos/luiisgallego.md
Se actualizan los objetivos hasta la fecha. Principalmente los nuevos objetivos corresponden a Docker, por lo que aún hay muchos sin realizar, los cuales serán completados en los próximos días con la realización de dicho hito.
=> actualizo objetivos hasta hoy

proyectos/hito-3.md
=> resend hito3

proyectos/hito-5.md
<https://github.com/jmv74211/CC-Ejercicios/tree/master/Objetivos>
Entrega del hito número 5 de la asignatura de cloud computing por parte de @jmv74211. En este hito he realizado la orquestación de dos máquinas virtuales utilizando vagrant y como proveedor de servicios cloud azure.
También he avanzado en la implementación, haciendo que el microservicio de tareas utilice el microservicio de usuarios para realizar la gestión de usuarios y acceso a la aplicación.
Se ha realizado la comprobación del hito 5 a @Gecofer.
- Aprovisionamiento de las máquinas: Modificaciones correspondientes para el aprovisionamiento de las dos máquinas virtuales.
- Test del avance del proyecto: Implementación de los nuevos test sobre la nuevas …
=> Añade enlace al hito 5 de @jmv74211

sesiones/11-semana.md
Enlace a ruta no existente en documentación.
=> Arreglado enlace para siguiente semana

proyectos/hito-5.md
Entrega del hito 5, en donde se usa `Vagrant` para provisionar una o preferiblemente varias máquinas virtuales usando un proveedor de servicios cloud, en este caso se ha usado Azure. En el directorio [orquestacion](https://github.com/Gecofer/proyecto-CC/tree/master/orquestacion) se encuentran los archivos necesarios para llevar a cabo la creación y provisión de las máquinas virtuales y la documentación se encuentra [aquí](https://github.com/Gecofer/proyecto-CC/blob/master/orquestacion/README.md). La documentación donde se explica el proceso para la creación y uso de la base de datos, se puede encontrar [aquí](https://github.com/Gecofer/proyecto-CC/blob/master/docs/avance_proyecto.md#id8).
[Hito 5 - Orquestación de máquinas …
=> Enlace para el hito 5

proyectos/hito-5.md
* [ X ] He leído el guión del hito
* [ X ] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [ X ] He actualizado con la última versión del fichero de entrega (y resto del repositorio).
Entrega del hito 5 de la asignatura Cloud Computing 2018/2019 sobre orquestación de máquinas virtuales
https://github.com/AlejandroCN7/Proyecto-Cloud-Computing/issues?q=is%3Aissue+is%3Aclosed+milestone%3A%22Orquestaci%C3%B3n+de+m%C3%A1quinas+virtuales%22
=> Entrega del hito5, Alejandro Campoy Nieves.

objetivos/gecofer.md
El enlace a los objetivos puede encontrarse [aquí](https://github.com/Gecofer/CC-18-19/blob/master/objetivos/gecofer.md), dentro se enlazan a los documentos pertinentes. 
Entrega de los objetivos del hito 5 y revisión de otros objetivos.
=> Objetivos del hito 5 y revisión de otros objetivos

objetivos/adrianmorente.md, proyectos/hito-4.md
[adrianmorente/objetivos.md](https://github.com/JJ/CC-18-19/blob/master/objetivos/adrianmorente.md)
Enumeración de los objetivos satisfechos y conceptos asimilados de forma previa a la entrega del hito 4 finalizado.
=> Entrego objetivos satisfechos hasta la terminación del hito 4

proyectos/hito-6.md
6
He creado un Dockerfile y comprobado que genera un contenedor correctamente. Además, lo he añadido a DockerHub y lo he desplegado en Heroku.
* [Hito 6: Docker](https://github.com/gomezportillo/apolo/milestone/7)
* [Crear un dockerfile](https://github.com/gomezportillo/apolo/issues/31)
* [Documentar docker](https://github.com/gomezportillo/apolo/issues/32)
=> Añadiendo hito 6

objetivos/migueldgoncalves.md
https://github.com/migueldgoncalves/CC-18-19/blob/solo-objetivos/objetivos/migueldgoncalves.md#duod%C3%A9cima-semana
https://github.com/migueldgoncalves/CC-18-19/blob/solo-objetivos/objetivos/migueldgoncalves.md#decimotercera-semana
Objetivos de las semanas 12 y 13
=> Entrega de los objetivos semanas 12 y 13

objetivos/xenahort.md
[Objetivos](https://github.com/JJ/CC-18-19/blob/master/objetivos/xenahort.md)
Añadidos objetivos del hito 6
=> Añado objetivos hito 6

proyectos/hito-4.md
https://github.com/jrtrillo/proyecto_cc
Se añade el hito 4
https://github.com/jrtrillo/proyecto_cc/issues/15
https://github.com/jrtrillo/proyecto_cc/issues/17
=> añadir hito 4

proyectos/hito-6.md
He creado un Dockerfile y comprobado que genera un contenedor correctamente. Además, lo he añadido a DockerHub y lo he desplegado en Heroku.
* [Hito 6: Docker](https://github.com/gomezportillo/apolo/milestone/7)
* [Crear un dockerfile](https://github.com/gomezportillo/apolo/issues/31)
* [Documentar docker](https://github.com/gomezportillo/apolo/issues/32)
=> Añadiendo hito 6.1

proyectos/hito-4.md
https://github.com/JJ/CC-18-19/blob/master/objetivos/danielbc09.md
* [ X] He leído el guión del hito
* [X ] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [X ] He actualizado con la última versión del fichero de entrega (y resto del repositorio).
* [X ] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
* [ X] He enlazado las actividades con el fichero de objetivos.
* [X ] He actualizado con la última versión del fichero de entrega y
Se desarrolla el Hito 4 con actualizaciones a la aplicación y Creación de una base de datos
Los issues van del 26 a la 36 en el milestone 4.
=> Hito 4 reenviado

proyectos/hito-6.md
Publicada versión 6 del proyecto con el código y documentación del mismo
* [Hito 6](https://github.com/fpeiro/CC-proyecto/milestone/7)
- [Adición de implementación de contenedores al proyecto](https://github.com/fpeiro/CC-proyecto/issues/24) (se han realizado contenedores y desplegado en Azure)
- [Información sobre el hito 6](https://github.com/fpeiro/CC-proyecto/issues/25) (se ha documentado lo realizado en el proyecto así como la integración con el resto de servicios)
- [Adición del CRUD de usuarios](https://github.com/fpeiro/CC-proyecto/issues/26) (se ha creado el cuarto microservicio correspondiente con la creación de usuarios y el …
=> Publicada versión 6 del proyecto

proyectos/hito-6.md
https://github.com/luiisgallego/CC-18-19/blob/master/objetivos/luiisgallego.md
Último hito de la asignatura, en el cual desplegamos contenedores mediante Docker. En esta ocasión no hay avance del proyecto.
De nuevo, hacemos uso de milestones, concretamente el 6. En este podemos encontrar los siguientes issues:
- [56](https://github.com/luiisgallego/MII_CC_1819/issues/56): Creación del *Dockerfile* con la base de datos *mlab*.
- [57](https://github.com/luiisgallego/MII_CC_1819/issues/57): Documentación completa.
=> entrega hito 6

proyectos/hito-6.md
Entrega del hito 6 de Cloud Computing por Alejandro Campoy Nieves.
=> Entrega del hito 6. Alejandro Campoy Nieves.

proyectos/hito-5.md
https://github.com/JJ/CC-18-19/blob/master/objetivos/migueldgoncalves.md#duod%C3%A9cima-semana
https://github.com/JJ/CC-18-19/blob/master/objetivos/migueldgoncalves.md#decimotercera-semana
Se ha limpio el hito 7 de los milestones (y se ha reabierto porque no pasaba los tests). Se ha añadido una base de datos MongoDB al microservicio de Información al Cliente. Se ha creado un nuevo microservicio, de Gestión de Viajes, completo con pruebas de clase, servicio web y integración con el otro microservicio. Se ha añadido la badge de Travis. Se ha creado un Vagrantfile capaz de orquestar los dos microservicios. El sistema operativo utilizado fue mejor justificado. Se ha actualizado toda la documentación y ficheros …
=> Entrega del hito 5

proyectos/hito-4.md
=> resend hito4

objetivos/AlejandroCN7.md
Actualizado mi fichero de objetivos. Alejandro Campoy Nieves.
=> Actualizados los objetivos. Alejandro Campoy Nieves

proyectos/hito-6.md
https://github.com/jmv74211/CC-Ejercicios/tree/master/Objetivos
Entrega del hito 6 de @jmv74211. Contenedores para despliegue en la nube
Este hito se corresponde con el milestone llamado hito 6. Este hito ha superado todos sus issues que son:
- Añadir Dockerfile: Creación de ficheros dockerfile para los dos microservicios.
- Documentación hito 6: Toda la documentación generada en el proceso de desarrollo de este hito.
- Actualización del fichero readme.md: Actualiza el readme con la información del hito 6
=> Añade hito 6 de @jmv74211

proyectos/hito-6.md
[objetivos](https://github.com/JJ/CC-18-19/blob/master/objetivos/alex1ai.md)
Hito 6: 
- Se introducí docker, docker-compose al proyecto. 
- Se usa docker-machine para desplegar el servicio web en Azure.
- Usa de variables entorno para secretos
Proyecto: 
- Se usa métodos de autentificación para permitir accesso a rutas de cambios (POST/PUT/DELETE) solo a personas autorizados.
- Refactoring
- question-Id handling on new inserts 
Milestone: [Introduce Docker](https://github.com/alex1ai/ugr-master-cc/milestone/8)
Issues:
- [30](https://github.com/alex1ai/ugr-master-cc/issues/30)
- [32](https://github.com/alex1ai/ugr-master-cc/issues/32)
- [33](https://github.com/alex1ai/ugr-master-cc/issues/33)
- [34](https://github.com/alex1ai/ugr-master-cc/issues/34)
- …
=> Entrega proyecto, hito final

objetivos/jrtrillo.md
https://github.com/jrtrillo/CC-18-19/blob/master/objetivos/jrtrillo.md
entrega hitos hasta el final
=> Añadir objetivos hasta el final

proyectos/hito-5.md
Entrega del hito 5
https://github.com/jrtrillo/proyecto_cc/issues/19
https://github.com/jrtrillo/proyecto_cc/issues/20
https://github.com/jrtrillo/proyecto_cc/issues/21
=> Añadir Hito 5

proyectos/hito-6.md
Entrega hito 6
https://github.com/jrtrillo/proyecto_cc/issues/23
https://github.com/jrtrillo/proyecto_cc/issues/24
=> añadir hito 6

objetivos/mesagon.md
Objetivos semanas 13, 14 y 15.
=> Añadir objetivos semanas 13, 14 y 15

proyectos/hito-5.md
https://github.com/JJ/CC-18-19/blob/master/objetivos/MarAl15.md
Se ha añadido la verificación de introducción de una fecha válida y se ha modificado la URL relacionada con MongoDB para que podamos acceder a la base de datos desde otra máquina.
Por otro lado, se ha realizado la creación, aprovisionamiento y despliegue con ayuda de Vagrant. Para ello se ha creado y provisionado dos máquinas virtuales en Azure a partir del Vagrantfile diseñado. Una de ellas contiene el servicio a desplegar y otra la base de datos relacionada con este. Además mi compañero Jesús Mesa y yo nos hemos comprobado mutuamente el correcto funcionamiento del Vagrantfile y el posterior despliegue de la aplicación.
[Hito 5: Orquestación de máquinas …
=> Enlace hito 5

objetivos/danielbc09.md
=> Objetivos Hito 6

proyectos/hito-5.md
=> added hito5

proyectos/hito-5.md
https://github.com/JJ/CC-18-19/blob/master/objetivos/danielbc09.md
Corrección Hito 5
https://github.com/danielbc09/Proyecto_CC/milestone/6
=> Reenvio Hito 5

proyectos/hito-6.md
https://github.com/JJ/CC-18-19/blob/master/objetivos/danielbc09.md
* [X ] He leído el guión del hito
* [X ] Cumplo los prerrequisitos (he aprobado el hito anterior, por ejemplo)
* [X ] He [seguido las instrucciones para reenvíos](http://jj.github.io/CC/documentos/proyecto/Reenvios) *sólo en caso de reenvío*.
Reenvío Hito 6 con los nuevos microservicios desplegados.
https://github.com/danielbc09/Proyecto_CC/milestone/7
=> Reenvío Hito 6

proyectos/hito-0.md
Corresponde al hito 0
Entrega del hito 0
=> Añado Hito 0

proyectos/hito-1.md
Reverts JJ/CC-18-19#412
I've checked this and there was an error in the script, but also an error in one of the issues that hadn't been closed by a commit. So please check it and sent it back again.
This was the error:
```
not ok 19 - El issue 23 se ha cerrado desde commit
```
=> Revert "resend hito1"

proyectos/hito-1.md
=> resend  milestone1

proyectos/hito-3.md
Reverts JJ/CC-18-19#423
La dirección no es alcanzable: `not ok 42 - 40.89.173.40 es alcanzable`
=> Revert "Añado hito 3"

proyectos/hito-6.md
Hito 6
Hito 6
* Crear Dockerfile
* Desplegar contenedores en azure
* Despliegue en local
* Explicar DockerHub
* Documentar
=> Añado Hito 6
